#!/bin/sh
### BEGIN INIT INFO
# Provides:          ghost
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/Stop/Restart/Reload local Ghost blog instance(s)
# Description:       Enable service provided by daemon.
### END INIT INFO

start(){
  
}

stop(){
  
}

restart(){
  
}

reload(){
  
}

status(){
  
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  reload)
    reload
    ;;
  status)
    status
    ;;
  *)
  echo "Usage: $0 {start|stop|restart|reload|status}"
esac

